language: python
python:
  - '2.7'
  - '3.6.3'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py db upgrade
script: coverage run manage.py test