"""empty message

Revision ID: 066ed2966344
Revises: 53ce436c31c2
Create Date: 2018-02-28 14:41:00.511718

"""

# revision identifiers, used by Alembic.
revision = '066ed2966344'
down_revision = '53ce436c31c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('excites', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('helps', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('who', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'who')
    op.drop_column('discussion_profiles', 'origin')
    op.drop_column('discussion_profiles', 'helps')
    op.drop_column('discussion_profiles', 'excites')
    ### end Alembic commands ###
