"""empty message

Revision ID: 0c14c17b64b0
Revises: 6ac291c17d75
Create Date: 2018-04-05 13:00:04.689592

"""

# revision identifiers, used by Alembic.
revision = '0c14c17b64b0'
down_revision = '6ac291c17d75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'public')
    ### end Alembic commands ###
