"""empty message

Revision ID: 1a58afbb802e
Revises: 6eabb7720292
Create Date: 2018-01-13 10:03:06.551017

"""

# revision identifiers, used by Alembic.
revision = '1a58afbb802e'
down_revision = '6eabb7720292'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeslots')
    ### end Alembic commands ###
