"""empty message

Revision ID: 1fef79595b53
Revises: 3cb6b0e276e9
Create Date: 2018-02-03 18:29:15.125642

"""

# revision identifiers, used by Alembic.
revision = '1fef79595b53'
down_revision = '3cb6b0e276e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('timezone', sa.String(), server_default='America/New_York', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'timezone')
    ### end Alembic commands ###
