"""empty message

Revision ID: 31d6b8c44241
Revises: e3cd6a6740d6
Create Date: 2018-02-19 11:53:40.923592

"""

# revision identifiers, used by Alembic.
revision = '31d6b8c44241'
down_revision = 'e3cd6a6740d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('stars', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'stars')
    ### end Alembic commands ###
