"""empty message

Revision ID: 347330a40c88
Revises: d3688e8b48fa
Create Date: 2018-02-17 19:43:00.330226

"""

# revision identifiers, used by Alembic.
revision = '347330a40c88'
down_revision = 'd3688e8b48fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requestExpert', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requestExpert')
    ### end Alembic commands ###
