"""empty message

Revision ID: 3cb6b0e276e9
Revises: 1a58afbb802e
Create Date: 2018-02-03 13:47:50.156228

"""

# revision identifiers, used by Alembic.
revision = '3cb6b0e276e9'
down_revision = '1a58afbb802e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'start_time')
    ### end Alembic commands ###
