"""empty message

Revision ID: 416f5aaca91b
Revises: f43e399079ba
Create Date: 2018-04-12 14:51:53.132079

"""

# revision identifiers, used by Alembic.
revision = '416f5aaca91b'
down_revision = 'f43e399079ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('github', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('medium', sa.String(), nullable=True))
    op.add_column('discussion_profiles', sa.Column('twitter', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'twitter')
    op.drop_column('discussion_profiles', 'medium')
    op.drop_column('discussion_profiles', 'linkedin')
    op.drop_column('discussion_profiles', 'github')
    ### end Alembic commands ###
