"""empty message

Revision ID: 4588c6bccb6d
Revises: 725f0c5080bd
Create Date: 2018-04-28 10:37:37.711961

"""

# revision identifiers, used by Alembic.
revision = '4588c6bccb6d'
down_revision = '725f0c5080bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslots', sa.Column('pending', sa.Boolean(), nullable=True))
    op.add_column('timeslots', sa.Column('pending_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslots', 'pending_time')
    op.drop_column('timeslots', 'pending')
    ### end Alembic commands ###
