"""empty message

Revision ID: 4bd5a068a5a4
Revises: 9e78529b2892
Create Date: 2018-01-01 15:20:39.563647

"""

# revision identifiers, used by Alembic.
revision = '4bd5a068a5a4'
down_revision = '9e78529b2892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), server_default='default name', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
