"""empty message

Revision ID: 53ce436c31c2
Revises: ee815d733e91
Create Date: 2018-02-19 16:43:30.516012

"""

# revision identifiers, used by Alembic.
revision = '53ce436c31c2'
down_revision = 'ee815d733e91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('guest_initials', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'guest_initials')
    ### end Alembic commands ###
