"""empty message

Revision ID: 6ac291c17d75
Revises: 9347e50b34de
Create Date: 2018-04-03 17:44:37.840324

"""

# revision identifiers, used by Alembic.
revision = '6ac291c17d75'
down_revision = '9347e50b34de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'url')
    ### end Alembic commands ###
