"""empty message

Revision ID: 6ade36e4d4b6
Revises: 4588c6bccb6d
Create Date: 2018-04-28 15:17:56.590391

"""

# revision identifiers, used by Alembic.
revision = '6ade36e4d4b6'
down_revision = '4588c6bccb6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('vipid', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'vipid')
    ### end Alembic commands ###
