"""empty message

Revision ID: 6eabb7720292
Revises: None
Create Date: 2018-01-07 11:09:05.693302

"""

# revision identifiers, used by Alembic.
revision = '6eabb7720292'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('area_code', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('auth_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('otherProfile', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='conversation_status_enum'), nullable=True),
    sa.Column('discussion_profile_id', sa.Integer(), nullable=True),
    sa.Column('guest_phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_profile_id'], ['discussion_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('discussion_profiles')
    op.drop_table('users')
    ### end Alembic commands ###
