"""empty message

Revision ID: 725f0c5080bd
Revises: bef9603a8e48
Create Date: 2018-04-27 11:59:45.116810

"""

# revision identifiers, used by Alembic.
revision = '725f0c5080bd'
down_revision = 'bef9603a8e48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_profiles', sa.Column('submitFull', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_profiles', 'submitFull')
    ### end Alembic commands ###
