"""empty message

Revision ID: 7776d9f40708
Revises: 066ed2966344
Create Date: 2018-03-02 11:08:34.831547

"""

# revision identifiers, used by Alembic.
revision = '7776d9f40708'
down_revision = '066ed2966344'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discussion_profiles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('discussion_profiles', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('discussion_profiles', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('discussion_profiles', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'America/New_York'::character varying"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discussion_profiles', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'America/New_York'::character varying"))
    op.alter_column('discussion_profiles', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('discussion_profiles', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('discussion_profiles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
