"""empty message

Revision ID: 7860e66c7618
Revises: f576c44a7bcd
Create Date: 2018-02-13 18:55:23.813691

"""

# revision identifiers, used by Alembic.
revision = '7860e66c7618'
down_revision = 'f576c44a7bcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', sa.String(length=128), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'password')
    ### end Alembic commands ###
