"""empty message

Revision ID: 7f182ba1ba87
Revises: None
Create Date: 2017-12-06 21:21:15.738471

"""

# revision identifiers, used by Alembic.
revision = '7f182ba1ba87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('area_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='conversation_status_enum'), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('discussion_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_profile_id'], ['discussion_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_table('discussion_profiles')
    op.drop_table('users')
    ### end Alembic commands ###
