"""empty message

Revision ID: 854b187f0a00
Revises: bb2a7efb7278
Create Date: 2018-02-18 15:54:46.041090

"""

# revision identifiers, used by Alembic.
revision = '854b187f0a00'
down_revision = 'bb2a7efb7278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('reviewed', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('unsubscribed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'unsubscribed')
    op.drop_column('conversations', 'reviewed')
    ### end Alembic commands ###
