"""empty message

Revision ID: 97a22c9334db
Revises: b08622ac6761
Create Date: 2017-12-30 20:54:09.118153

"""

# revision identifiers, used by Alembic.
revision = '97a22c9334db'
down_revision = 'b08622ac6761'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column(u'conversations', sa.Column('guest_phone_number', sa.String(), nullable=True))
    op.drop_constraint(u'conversations_guest_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column(u'conversations', 'guest_id')
    op.add_column(u'users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column(u'users', sa.Column('registered_on', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column(u'users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column(u'users', 'registered_on')
    op.drop_column(u'users', 'admin')
    op.add_column(u'conversations', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'conversations_guest_id_fkey', 'conversations', 'users', ['guest_id'], ['id'])
    op.drop_column(u'conversations', 'guest_phone_number')
    op.drop_table('blacklist_tokens')
    ### end Alembic commands ###
