"""empty message

Revision ID: a19db505d5e8
Revises: 7f182ba1ba87
Create Date: 2017-12-17 14:13:39.855938

"""

# revision identifiers, used by Alembic.
revision = 'a19db505d5e8'
down_revision = '7f182ba1ba87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('guest_phone_number', sa.String(), nullable=True))
    op.drop_constraint(u'conversations_guest_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'guest_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'conversations_guest_id_fkey', 'conversations', 'users', ['guest_id'], ['id'])
    op.drop_column('conversations', 'guest_phone_number')
    ### end Alembic commands ###
