"""empty message

Revision ID: b45d0927ac92
Revises: 31d6b8c44241
Create Date: 2018-02-19 15:00:20.175408

"""

# revision identifiers, used by Alembic.
revision = 'b45d0927ac92'
down_revision = '31d6b8c44241'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_host_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'host_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_host_id_fkey', 'reviews', 'users', ['host_id'], ['id'])
    ### end Alembic commands ###
