"""empty message

Revision ID: b9098267c251
Revises: f6bfa22eb6d8
Create Date: 2018-04-21 11:38:14.343136

"""

# revision identifiers, used by Alembic.
revision = 'b9098267c251'
down_revision = 'f6bfa22eb6d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('call_timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'call_timestamp')
    ### end Alembic commands ###
