"""empty message

Revision ID: bb2a7efb7278
Revises: 347330a40c88
Create Date: 2018-02-17 20:56:28.437035

"""

# revision identifiers, used by Alembic.
revision = 'bb2a7efb7278'
down_revision = '347330a40c88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messageforAdmins', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'messageforAdmins')
    ### end Alembic commands ###
