"""empty message

Revision ID: c0fa1a7bfb44
Revises: 1bece49284fd
Create Date: 2018-01-06 10:48:51.584364

"""

# revision identifiers, used by Alembic.
revision = 'c0fa1a7bfb44'
down_revision = '1bece49284fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_pic', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_pic')
    ### end Alembic commands ###
