"""empty message

Revision ID: c51fb7c99043
Revises: ad17315dd1b5
Create Date: 2017-12-04 21:14:53.625731

"""

# revision identifiers, used by Alembic.
revision = 'c51fb7c99043'
down_revision = 'ad17315dd1b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'anonymous_phone_number')
    op.add_column('vacation_properties', sa.Column('anonymous_phone_number', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_properties', 'anonymous_phone_number')
    op.add_column('reservations', sa.Column('anonymous_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
