"""empty message

Revision ID: d3688e8b48fa
Revises: e2ff2c83f945
Create Date: 2018-02-17 14:33:39.978260

"""

# revision identifiers, used by Alembic.
revision = 'd3688e8b48fa'
down_revision = 'e2ff2c83f945'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['guest_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'guest_id')
    ### end Alembic commands ###
