"""empty message

Revision ID: e2ff2c83f945
Revises: 25ec89657355
Create Date: 2018-02-14 22:23:55.737784

"""

# revision identifiers, used by Alembic.
revision = 'e2ff2c83f945'
down_revision = '25ec89657355'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'expert',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'expert',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    ### end Alembic commands ###
