"""empty message

Revision ID: e3cd6a6740d6
Revises: f2104328f298
Create Date: 2018-02-19 11:53:31.459486

"""

# revision identifiers, used by Alembic.
revision = 'e3cd6a6740d6'
down_revision = 'f2104328f298'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('reviews', 'stars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('stars', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('reviews', 'comment',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    ### end Alembic commands ###
