"""empty message

Revision ID: e3f71d701f9c
Revises: b45d0927ac92
Create Date: 2018-02-19 15:09:53.709209

"""

# revision identifiers, used by Alembic.
revision = 'e3f71d701f9c'
down_revision = 'b45d0927ac92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['host_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'host_id')
    ### end Alembic commands ###
