"""empty message

Revision ID: ee815d733e91
Revises: e3f71d701f9c
Create Date: 2018-02-19 15:14:40.183007

"""

# revision identifiers, used by Alembic.
revision = 'ee815d733e91'
down_revision = 'e3f71d701f9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('guest_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'guest_id')
    ### end Alembic commands ###
