"""empty message

Revision ID: f2104328f298
Revises: 854b187f0a00
Create Date: 2018-02-18 20:42:15.866478

"""

# revision identifiers, used by Alembic.
revision = 'f2104328f298'
down_revision = '854b187f0a00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.DateTime(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    ### end Alembic commands ###
