"""empty message

Revision ID: f43e399079ba
Revises: f5d9a1ef185e
Create Date: 2018-04-06 17:15:27.722171

"""

# revision identifiers, used by Alembic.
revision = 'f43e399079ba'
down_revision = 'f5d9a1ef185e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('guest_email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'guest_email')
    ### end Alembic commands ###
