"""empty message

Revision ID: f576c44a7bcd
Revises: 1fef79595b53
Create Date: 2018-02-13 18:22:58.710521

"""

# revision identifiers, used by Alembic.
revision = 'f576c44a7bcd'
down_revision = '1fef79595b53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    ### end Alembic commands ###
