"""empty message

Revision ID: f6bfa22eb6d8
Revises: fbc2e3670e8e
Create Date: 2018-04-20 20:30:47.232308

"""

# revision identifiers, used by Alembic.
revision = 'f6bfa22eb6d8'
down_revision = 'fbc2e3670e8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('call_duration', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('call_status', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('caller_sid', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('parent_call_sid', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'parent_call_sid')
    op.drop_column('conversations', 'caller_sid')
    op.drop_column('conversations', 'call_status')
    op.drop_column('conversations', 'call_duration')
    ### end Alembic commands ###
