"""empty message

Revision ID: fbc2e3670e8e
Revises: 88e67836a647
Create Date: 2018-04-20 18:14:36.003316

"""

# revision identifiers, used by Alembic.
revision = 'fbc2e3670e8e'
down_revision = '88e67836a647'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('review_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'review_id')
    ### end Alembic commands ###
